# Site settings
title: Your WordPress Questions, Answered
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Making the most of WordPress means being able to navigate the
  diverse landscape of hosting providers and the many options they
  offer.  This site is a collection of answers to the questions you
  may have, helping you make the most of what you have.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://osmanual2hosting.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username: jekyll

# Build settings
markdown: kramdown
